# Generated by Django 6.0.1 on 2026-01-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL of the trip cover image', max_length=500, null=True),
        ),
    ]
