# Generated by Django 5.0.2 on 2026-02-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_add_location_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripWeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(help_text='Temperature in Celsius')),
                ('condition', models.CharField(help_text='Weather condition (e.g., Clear, Clouds, Rain)', max_length=50)),
                ('description', models.CharField(help_text='Detailed weather description', max_length=100)),
                ('icon', models.CharField(help_text='OpenWeather icon code', max_length=10)),
                ('city_name', models.CharField(blank=True, default='', help_text='City name from weather API', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When the cache was last updated')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_cache', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Weather Cache',
                'verbose_name_plural': 'Trip Weather Caches',
            },
        ),
    ]
