# Generated by Django 6.0.1 on 2026-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_tripimage_database_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripmember',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('left', 'Left')], default='invited', max_length=20),
        ),
    ]
