# Generated by Django 6.0.1 on 2026-01-23 19:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Compatibility score from 0 to 100', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_user', models.ForeignKey(help_text='The matched potential buddy', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_matched_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user seeking matches', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buddy Match',
                'verbose_name_plural': 'Buddy Matches',
                'ordering': ['-match_score', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('user', models.F('matched_user')), _negated=True), name='prevent_self_match')],
                'unique_together': {('user', 'matched_user')},
            },
        ),
    ]
