# Generated by Django 6.0.1 on 2026-01-26 15:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Compatibility score from 0 to 100', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_user', models.ForeignKey(help_text='The matched potential buddy', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_matched_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user seeking matches', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buddy Match',
                'verbose_name_plural': 'Buddy Matches',
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('user', 'matched_user')},
            },
        ),
        migrations.CreateModel(
            name='BuddyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the request', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(help_text='User who received the request', on_delete=django.db.models.deletion.CASCADE, related_name='received_buddy_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_buddy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buddy Request',
                'verbose_name_plural': 'Buddy Requests',
                'ordering': ['-created_at'],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
