# Generated by Django 6.0.1 on 2026-01-23 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the request', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(help_text='User who received the request', on_delete=django.db.models.deletion.CASCADE, related_name='received_buddy_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_buddy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buddy Request',
                'verbose_name_plural': 'Buddy Requests',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='prevent_self_request')],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
