# Generated by Django 5.0.2 on 2026-01-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddymatch',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='connected', help_text='Connection status', max_length=20),
        ),
    ]
