# Generated by Django 6.0.1 on 2026-01-26 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_range', models.CharField(choices=[('low', 'Low ($0 - $1000)'), ('medium', 'Medium ($1000 - $3000)'), ('high', 'High ($3000+)')], help_text='Preferred budget range for trips', max_length=20)),
                ('travel_style', models.CharField(choices=[('solo', 'Solo'), ('group', 'Group'), ('family', 'Family'), ('adventure', 'Adventure'), ('leisure', 'Leisure')], help_text='Preferred travel style', max_length=20)),
                ('preferred_trip_duration', models.CharField(choices=[('weekend', 'Weekend (2-3 days)'), ('short', 'Short (4-7 days)'), ('long', 'Long (1-2 weeks+)')], help_text='Preferred duration of trips', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='PreferenceInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.interest')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.preference')),
            ],
            options={
                'verbose_name': 'Preference Interest',
                'verbose_name_plural': 'Preference Interests',
                'unique_together': {('preference', 'interest')},
            },
        ),
        migrations.AddField(
            model_name='preference',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='preferences', through='preferences.PreferenceInterest', to='preferences.interest'),
        ),
    ]
