# Generated by Django 5.0.2 on 2026-02-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_add_opentripmap_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationImageCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, help_text='Search query used for Unsplash lookup', max_length=500, unique=True)),
                ('image_url', models.URLField(help_text='Resolved image URL from Unsplash', max_length=1000)),
                ('image_source', models.CharField(default='unsplash', help_text='Source of the image: unsplash or fallback', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destination Image Cache',
                'verbose_name_plural': 'Destination Image Caches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='tripsaveddestination',
            options={'ordering': ['order', '-saved_at']},
        ),
    ]
