# Generated by Django 5.0.2 on 2026-02-19 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_destinationimagecache_and_more'),
        ('trips', '0003_tripweathercache'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='Cached recommendation data organized by category')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='Generation status of recommendations', max_length=10)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if generation failed')),
                ('last_generated', models.DateTimeField(auto_now=True, help_text='When recommendations were last generated')),
                ('expires_at', models.DateTimeField(help_text='When this cache should be considered stale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(help_text='Trip these recommendations are for', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_cache', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Recommendation Cache',
                'verbose_name_plural': 'Trip Recommendation Caches',
                'ordering': ['-last_generated'],
                'indexes': [models.Index(fields=['trip', 'status'], name='recommendat_trip_id_5dc573_idx'), models.Index(fields=['expires_at'], name='recommendat_expires_0a655f_idx')],
            },
        ),
    ]
