# Generated by Django 5.0.2 on 2026-03-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_triprecommendationcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Culture', 'Culture'), ('Heritage', 'Heritage'), ('Adventure', 'Adventure'), ('Attraction', 'Attraction')], max_length=20),
        ),
    ]
