# Generated by Django 5.0.2 on 2026-02-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconversation',
            name='last_buddy_offset',
            field=models.IntegerField(default=0, help_text='Pagination offset for buddy suggestions'),
        ),
    ]
