# Generated by Django 5.0.2 on 2026-01-23 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buddy_request_sent', 'Buddy Request Sent'), ('buddy_request_received', 'Buddy Request Received'), ('buddy_request_accepted', 'Buddy Request Accepted'), ('buddy_request_rejected', 'Buddy Request Rejected')], help_text='Type of notification', max_length=30)),
                ('message', models.TextField(help_text='Notification message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of the related object (e.g., BuddyRequest ID)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
