# Generated by Django 6.0.1 on 2026-01-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, help_text='ID of the related object (e.g., BuddyRequest ID, Trip ID)', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('buddy_request_sent', 'Buddy Request Sent'), ('buddy_request_received', 'Buddy Request Received'), ('buddy_request_accepted', 'Buddy Request Accepted'), ('buddy_request_rejected', 'Buddy Request Rejected'), ('trip_invite_sent', 'Trip Invite Sent'), ('trip_invite_received', 'Trip Invite Received'), ('trip_invite_accepted', 'Trip Invite Accepted'), ('trip_invite_rejected', 'Trip Invite Rejected'), ('destination_saved', 'Destination Saved'), ('member_left_trip', 'Member Left Trip')], help_text='Type of notification', max_length=30),
        ),
    ]
