# Generated by Django 5.0.2 on 2026-01-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for the notification (e.g., sender_id, buddy_request_id)', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('buddy_request_sent', 'Buddy Request Sent'), ('buddy_request_received', 'Buddy Request Received'), ('buddy_request_accepted', 'Buddy Request Accepted'), ('buddy_request_rejected', 'Buddy Request Rejected'), ('trip_invite_sent', 'Trip Invite Sent'), ('trip_invite_received', 'Trip Invite Received'), ('trip_invite_accepted', 'Trip Invite Accepted'), ('trip_invite_rejected', 'Trip Invite Rejected'), ('destination_saved', 'Destination Saved'), ('member_left_trip', 'Member Left Trip'), ('trip_member_removed', 'Trip Member Removed'), ('trip_cancelled', 'Trip Cancelled')], help_text='Type of notification', max_length=30),
        ),
    ]
