# Generated by Django 5.0.2 on 2026-01-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_metadata_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('buddy_request_sent', 'Buddy Request Sent'), ('buddy_request_received', 'Buddy Request Received'), ('buddy_request_accepted', 'Buddy Request Accepted'), ('buddy_request_rejected', 'Buddy Request Rejected'), ('buddy_disconnected', 'Buddy Disconnected'), ('trip_invite_sent', 'Trip Invite Sent'), ('trip_invite_received', 'Trip Invite Received'), ('trip_invite_accepted', 'Trip Invite Accepted'), ('trip_invite_rejected', 'Trip Invite Rejected'), ('destination_saved', 'Destination Saved'), ('member_left_trip', 'Member Left Trip'), ('trip_member_removed', 'Trip Member Removed'), ('trip_cancelled', 'Trip Cancelled')], help_text='Type of notification', max_length=30),
        ),
    ]
